apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aether.fullname" . }}-kafka
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: {{ include "aether.fullname" . }}-kafka
  replicas: {{ .Values.databases.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: kafka
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka
          image: {{ .Values.databases.kafka.image }}
          ports:
            - containerPort: 9092
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.databases.kafka.storage }}

