apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aether.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: {{ include "aether.fullname" . }}-redis
  replicas: {{ .Values.databases.redis.replicas }}
  selector:
    matchLabels:
      app: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.databases.redis.image }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.databases.redis.storage }}

